---refernece document : HOW TO LINK THE TRANSACTION_SOURCE_ID TO TRANSACTION_SOURCE_TYPE_ID (Doc ID 987471.1)
--
SELECT
mmt.transaction_type_id,
mtt.transaction_type_name,
mmt.TRANSACTION_SOURCE_ID,
CASE 
WHEN mmt.TRANSACTION_SOURCE_TYPE_ID = 1 THEN (SELECT 'RSH_NUMBER: ' || RCV.SHIPMENT_NUM    ----PO¦¬³f/RMA Receipt
FROM RCV_SHIPMENT_HEADERS RCV,
RCV_TRANSACTIONS RCVT
WHERE RCV.SHIPMENT_HEADER_ID = RCVT.SHIPMENT_HEADER_ID
AND RCVT.TRANSACTION_ID = mmt.TRANSACTION_SOURCE_ID)
--
WHEN mmt.TRANSACTION_SOURCE_TYPE_ID = 2 THEN (SELECT 'SO_NUMBER: ' || SEGMENT1                 ---- Sales Order
FROM MTL_SALES_ORDERS
WHERE SALES_ORDER_ID = mmt.TRANSACTION_SOURCE_ID)
--
WHEN mmt.TRANSACTION_SOURCE_TYPE_ID = 4 THEN (SELECT 'MO_NUMBER: ' || REQUEST_NUMBER    --- Move Order
FROM MTL_TXN_REQUEST_HEADERS
WHERE REQUEST_NUMBER = TO_CHAR(mmt.TRANSACTION_SOURCE_ID))
--
WHEN mmt.TRANSACTION_SOURCE_TYPE_ID = 5 THEN (SELECT 'WIP_NUMBER: ' || WIP_ENTITY_NAME   --- Job or Schedule
FROM WIP_ENTITIES
WHERE WIP_ENTITY_ID = mmt.TRANSACTION_SOURCE_ID)
--
WHEN mmt.TRANSACTION_SOURCE_TYPE_ID = 7 THEN (SELECT 'INT_REQ_NUMBER: ' || RCV.SHIPMENT_NUM    ---Internal requisition
FROM RCV_SHIPMENT_HEADERS RCV,
RCV_TRANSACTIONS RCVT
WHERE RCV.SHIPMENT_HEADER_ID = RCVT.SHIPMENT_HEADER_ID
AND RCVT.TRANSACTION_ID = mmt.TRANSACTION_SOURCE_ID)
--
WHEN mmt.TRANSACTION_SOURCE_TYPE_ID = 8 THEN (SELECT 'INT_SO_NUMBER: ' || SEGMENT1       ----Internal order
FROM MTL_SALES_ORDERS
WHERE SALES_ORDER_ID = mmt.TRANSACTION_SOURCE_ID)
--
WHEN mmt.TRANSACTION_SOURCE_TYPE_ID = 10 THEN (SELECT 'PHY_NAME: ' || PHYSICAL_INVENTORY_NAME   ---½LÂI
FROM MTL_PHYSICAL_INVENTORIES
WHERE PHYSICAL_INVENTORY_ID = mmt.TRANSACTION_SOURCE_ID)
--
WHEN mmt.TRANSACTION_SOURCE_TYPE_ID = 12 THEN (SELECT 'RMA_NUMBER: ' || SEGMENT1                 ---- RMA Order
FROM MTL_SALES_ORDERS
WHERE SALES_ORDER_ID = mmt.TRANSACTION_SOURCE_ID)
--
ELSE  'Other Reference: ' || nvl(mmt.TRANSACTION_SOURCE_NAME , mmt.TRANSACTION_REFERENCE)
END SRC_NUMBER 
, MMT.*
--
FROM
mtl_transaction_types      mtt, 
MTL_MATERIAL_TRANSACTIONS  MMT
where 1=1
and mmt.transaction_type_id = mtt.transaction_type_id


/* remark
See the correnpondances below:
a)TRANSACTION_SOURCE_ID: Job or Schedule WIP_ENTITIES.WIP_ENTITY_ID
TRANSACTION_SOURCE_TYPE_ID = 5

b) TRANSACTION_SOURCE_ID: Sales Order MTL_SALES_ORDERS.SALES_ORDER_ID
TRANSACTION_SOURCE_TYPE_ID = 2, 8, 12, 13

c) TRANSACTION_SOURCE_ID: Account Alias MTL_GENERIC_DISPOSITIONS.DISPOSITION_ID
TRANSACTION_SOURCE_TYPE_ID = 6

d) TRANSACTION_SOURCE_ID: Purchase Order PO_HEADERS_ALL.PO_HEADER_ID
TRANSACTION_SOURCE_TYPE_ID = 1

e) TRANSACTION_SOURCE_ID: Account GL_CODE_COMBINATIONS.CODE_COMBINATION_ID
TRANSACTION_SOURCE_TYPE_ID = all others

*/